
server:
  port: 8080

spring:
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: true

  datasource:
    url: jdbc:mysql://localhost:3306/tutorial?serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

# linea de prueba