server:
  port: 8080

spring:
  data:
    rest:
      base-path: /api

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: true

  datasource:
    url: jdbc:mysql://localhost:3306/trikaBD
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
