export const VIEW_TASK_LIST = 'VIEW_TASK_LIST';

export const VIEW_COURSES_LIST = 'VIEW_COURSES_LIST';
export const VIEW_COURSES_LIST_TOTAL = 'VIEW_COURSES_LIST_TOTAL';
export const VIEW_VIDEOS_LIST = 'VIEW_VIDEOS_LIST';
export const VIEW_VIDEOS_COURSE_LIST = 'VIEW_VIDEOS_COURSE_LIST';
export const CREATE_CURSOES='CREATE_CURSOES';